
# docker-compose.yml

services:
  ray-head:
    build: .
    container_name: ray-head
    ports:
      - "8265:8265"
      - "10001:10001"
    # La clave es añadir la sección --resources
    command: |
      bash -c "
        ray start --head --num-cpus=1 --port=6379 --dashboard-host=0.0.0.0 --include-dashboard=true --ray-client-server-port=10001 --resources='{\"is_head_node\": 1}' && \
        echo 'Nodo HEAD en marcha...' && \
        tail -f /dev/null
      "
    shm_size: 2gb

  ray-worker-1:
    build: .
    container_name: ray-worker-1
    depends_on:
      - ray-head
    command: |
      bash -c "
        ray start --address=ray-head:6379 --num-cpus=2 && \
        echo 'Worker 1 conectado al HEAD' && \
        tail -f /dev/null
      "
    shm_size: 2gb

  ray-worker-2:
    build: .
    container_name: ray-worker-2
    depends_on:
      - ray-head
    command: |
      bash -c "
        # Comando simplificado, ya no crea el actor
        ray start --address=ray-head:6379 --num-cpus=2 && \
        echo 'Worker 2 conectado al HEAD' && \
        tail -f /dev/null
      "
    shm_size: 2gb
  
  management-api:
    build: .
    container_name: management-api
    depends_on:
      - ray-head
    ports:
      - "9000:9000"
    environment:
      # Asegúrate de que la API se conecta como cliente al head node
      - RAY_ADDRESS=ray://ray-head:10001
    command: uvicorn management_api:app --host 0.0.0.0 --port 9000
    restart: on-failure

  api-service:
    build: .
    container_name: api-service
    depends_on:
      - ray-head
    ports:
      - "8000:8000"
    environment:
      - RAY_ADDRESS=ray://ray-head:10001
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    restart: on-failure

  gui-service:
    build: .
    container_name: gui-service
    depends_on:
      - api-service
      - management-api
    ports:
      - "8501:8501"
    environment:
      # URLs para que la GUI sepa a dónde apuntar
      - MANAGEMENT_API_URL=http://management-api:9000
      - INFERENCE_API_URL=http://api-service:8000
      - RAY_DASHBOARD_URL=http://ray-head:8265
      - RAY_ADDRESS=ray://ray-head:10001
    command: |
      bash -c "
        echo 'GUI Service: Iniciando script de espera...'
        python wait_for_services.py && \
        echo 'GUI Service: Todas las APIs están listas, iniciando Streamlit...' && \
        streamlit run gui.py --server.port=8501 --server.address=0.0.0.0
      "
    restart: on-failure